import Head from 'next/head'
import Header from '../components/layout/Header'
import Main from '../components/landing/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by Masha" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <Main />

    </div>
  )
}
