import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Header from '../components/layout/Header'
import Main from '../components/landing/Main'

import { getTariffs } from '../lib/tariffs'

export async function getServerSideProps() {
  let tariffs = []
  try {
    tariffs = await getTariffs()
  } catch (e) {
    console.error('Failed to fetch tariffs:', e)
  }
  return { props: { tariffs } }
}

export default function Home({ tariffs: initialTariffs }) {
  const [timerEnded, setTimerEnded] = useState(false)
  const [tariffs, setTariffs] = useState(initialTariffs ?? [])

  // If server didn't return tariffs (e.g. fetch failed), load from API on client
  useEffect(() => {
    if (Array.isArray(tariffs) && tariffs.length > 0) return
    let cancelled = false
    fetch('/api/tariffs')
      .then((res) => res.json())
      .then((data) => {
        if (!cancelled && data?.tariffs?.length) setTariffs(data.tariffs)
      })
      .catch((e) => console.error('Client tariffs fetch failed:', e))
    return () => { cancelled = true }
  }, [])

  return (
    <div>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by Masha" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header onTimerEnd={() => setTimerEnded(true)} />
      <Main tariffs={tariffs} timerEnded={timerEnded} />
    </div>
  )
}
